FROM microsoft/dotnet:2.0-sdk AS build-env

RUN apt-get update 

WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy and build everything else
COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.0-runtime

RUN apt-get update 

WORKDIR /app

COPY --from=build-env /app/out ./

EXPOSE 5051

ENTRYPOINT ["dotnet", "GoCDTest.dll"]