FROM gocd/gocd-agent-ubuntu-16.04:v17.8.0

#Install .net core SDK
RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list' \
     && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EB3E94ADBE1229CF \
    && apt-get install -y apt-transport-https \
    && apt-get update \
    && apt-get install -y dotnet-sdk-2.0.0

# Trigger the population of the local package cache
ENV NUGET_XMLDOC_MODE skip
RUN mkdir warmup \
    && cd warmup \
    && dotnet new \
    && cd .. \
    && rm -rf warmup \
    && rm -rf /tmp/NuGetScratch

#Install Docker
RUN apt-get update \
	&& apt-get install docker.io -y

# add to docker group
RUN usermod -aG staff go

RUN mkdir converter 
COPY XMLConverter.dll ./converter
COPY XMLConverter.runtimeconfig.json ./converter
